.TH "t1c2pfb" "1" "October 2005" "cm-super" "cm-super" 
.PP 
.SH "NAME" 
pfb2t1c \- convert from binary PostScript Type1 into compressible \.t1c
t1c2pfb \- convert from compressible \.t1c to binary PostScript Type1
.PP 
.SH "SYNOPSIS" 
.PP 
\fBpfb2t1c\fP "pfb file"
.PP
\fBt1c2pfb\fP
.PP 
.SH "DESCRIPTION" 
.PP 
\fBpfb2t1c\fP reads a pfb file and converts it into the t1c format. The
resulting single file (written to stdout) is not much smaller than the
original pfb but more compressible. The file name of the pfb file(s) is/are
noted in a pseudo header inside the t1c, hence one can append the resulting
t1c files to each other.
.PP
\fBt1c2pfb\fP extracts fonts saved in a t1c file. The program reads from
stdin and creates the PostScript Type1 file(s).
.PP 
.SH COPYRIGHT
Copyright \(co 2003 Szab\['o] P\['e]ter.
.PP
There is NO warranty. The programs are released under GPL. See the copyright
file for details.
.SH "BUGS" 
.PP 
Problems with the programs should first reported into the Debian Bug Tracking
system, we will forward it to upstream if necessary.
.PP 
.SH "AUTHOR" 
.PP 
Written by pts@fazekas\&.hu\&.
.PP 
This manual page was written by Norbert Preining for
the Debian GNU/Linux system (and modified by Hilmar Preusse later)\&.  It may
be used by other distributions without contacting the author\&.  Any
mistakes or omissions in the manual page are my fault; inquiries about or
corrections to this manual page should be directed to me (and not to the
primary author)\&.
